### ISSUE TITLE
It will be much better if traceID and spanID use string.

### ISSUE THREAD

**Issue by xiaoshuang-lu** [openzipkin/zipkin-support#15]
Nowadays, zipkin uses long to describe both traceID and spanID.  This is an obstacle for third-party frameworks to leverage zipkin since not every ID is long. By contrast, string has less limitations.

**Comment by codefromthecrypt** [comment]
@CharlyRipp jaeger is a fork of zipkin and use exactly the same IDs as we do. Some libraries represent the 64-bit random data as a long or a lower-hex string. Between process is the part that matters and they marshal the same way, just uber has a historical header they sometimes use instead of B3, which is slightly different than our "b3" single header. Maybe hop on https://gitter.im/openzipkin/zipkin to clarify what you're asking as interop between zipkin and jaeger (I assume you mean client/tracer libraries) should be easy peasy

**Comment by CharlyRipp** [comment]
@adriancole Makes sense! I knew jaeger was a fork, just didn't know how far the differences went. I think you answered exactly what I needed though. Thanks! Sadly most employers I know have blocked gitter as social media :(

**Comment by codefromthecrypt** [comment]
No problem. we added this repo since some block or choose not to authorize gitter to their personal data
