### ISSUE TITLE
Client annotation address is unknown in lens

### ISSUE THREAD

**Issue by rmannibucau** [openzipkin/zipkin-support#16]
## Describe the Bug + Steps to reproduce
Generate a client span with a remote endpoint correctly setup - with a parent server span indeed.
Go in lens to see the span.
Open the annotations of the client span, Address is "unknown" instead of the IP of the remote endpoint.

## Expected Behaviour
Adress should be the one of the remote endpoint.

It seems it comes from https://github.com/openzipkin/zipkin/blob/master/zipkin-lens/src/zipkin/span-row.js#L58, line should likely be:

    const localFormatted = formatEndpoint(span.localEndpoint) || formatEndpoint(span.remoteEndpoint) || undefined;

(indeed you can add validation on "kind" if you feel it better)

**Comment by rmannibucau** [comment]
@adriancole hmm, think I'm not following you, in all cases lens use local endpoint but SERVER and CLIENT spans don't use localEndpoint so in one case it is wrong anyway whatever until the data you send to zipkin are always using localendpoint which is quite unlikely, no?

**Comment by codefromthecrypt** [comment]
localEndpoint is the thing that recorded the data. it is only optional in
the case of patching an existing span.


remoteEndpoint is the other side and optional. usually only the IP:port but
service name also when known.

tracers typically initialize a constant value for localEndpoint and use it
for all spans. that is why I am curious what is creating this data as it
looks strange.

you can look at this if helps
https://github.com/openzipkin/zipkin-api/blob/master/zipkin2-api.yaml#L483

**Comment by rmannibucau** [comment]
@adriancole the generator is a custom tracer but having local and remote endpoints at the same time is weird and created issues at some points so not sure we should have both anyway. Also it is weird since the UI gives you the local endpoint with the server span (which should always exist for a client one) so it just looks duplicated and eating network bandwidth, no?

**Comment by codefromthecrypt** [comment]
indexing happens on a span by span basis. traces are reported by different
nodes. messages including things can have mixed order etc. most
instrumentation dont have a concept of local root to know when something
starts and stops. spans can be between server and client also.

the UI doesnt currently guess what the endpoints should be when missing but
even if it did it would have to consistently guess.. the input data would
need to be correct.

I can understand you being curious just that this load generator is not
representative of correct data uses. also we have a lot of work to do and
it is volunteer run project. I hope these notes I have given can help you
but I am a bit over budget on this topic. good luck!

**Comment by rmannibucau** [comment]
@adriancole this is actually not related to endpoints. Indexing happens based on id as in most solution of that category (parent id, tx id) so endpoints are purely metadata (annotations), just promoted as more important than others. In such context, requiring local endpoint on both server and client is very inconsistent and should be fixed anyway IMHO. I can see a client span local endpoint being used while its parent server span is not there but it is a very fragile asumption in the case of a cluster so sticking to id is the only relevant way to show understable data. Endpoints are really only meaningful as metadata and should be represented as such.

**Comment by codefromthecrypt** [comment]
service name is a primary index field. it has been since 2012. we have to render the existing community and properly written tools. we have service aggregations all over zipkin. when people implement incorrectly as sometimes happen we try to steer them in the right place. aggregation requires a stable field and a stable meaning of it. if we randomly broke this meaning due to a conversation about the confused data you have pasted so far it would be a disservice to thousands of people.

you can feel free to fork since you seem to think you know better. you might run into similar problems though and when you do, I hope notes we have made help

**Comment by rmannibucau** [comment]
Hmm, this cant break the community since it enhances current support, works in grafana and works in several proprietary systems so I think your last statement emphasis a bit too much history - and yes we alread had this kind of impl at least 3 times and it works well.
What would be ok too is to hide unknown values, would be saner than showing that it is unknown when field is not fully required.

**Comment by codefromthecrypt** [comment]
The reason unknown is set is because most people except you would see this as a problem. It is historical, but it is also current. Also, you are asking about our UI and wanting us to change it. I don't think you would be able to assess what most zipkin users need better than a primary maintainer of the project for the last 5 years. Please correct your data or agree not to and stop bickering as it will lower motivations to help you when things are unnecessarily arduous.
